---
title: "test"
format: html
editor: visual
---
```{r}
labels: setup
library(tidyverse)
```



## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code.
You can embed code like this:

```{r}
df <- data.frame(x = 1:3, y = letters[1:3], z = LETTERS[1:3])

```

You can add options to executable code like this

```{r}
df
```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}df1 <- data.frame(x = 1:3, y = letters[1:3], z = LETTERS[1:3]), z = df}

```

```{r}
df <- data.frame(x = 1:3, y = letters[1:3], z = LETTERS[1:3])
```

```{r}
df1 <- data.frame(x = 1:3, y = letters[1:3], 
                 z = df)
```

```{r}
df1

```

```{r}
df$q <- c(2.1, 0.4, 0.9)
```

```{r}
df

```

### Hente info. ut av dataframe

```{r}
df$q

```
```{r}
str(df$q)
```

```{r}
dim(df)
```
```{r}
dim(df$q)
```

```{r}
length(df$q)


```
```{r}
as_tibble(df)
```


```{r}
class(mtcars)
```



```



```


```{r}
mtcars <- as_tibble(mtcars)
```

```{r}
mtcars
```

```{r}
#| paged.print: false
head(cars, n = -4)
```
```{r}
#| paged.print: false
tail(cars, n = -4L)
```

```{r}
plot(cars)
lm1 <- lm(formula = dist ~ speed, data = cars)
abline(lm1)
```
```{r}
summary(lm1)
```
```{r}
# multiple regression
# LifeCycleSavings from package Datasets
mreg1 <- lm(
  formula =sr ~ pop15 + pop75 + dpi + ddpi, 
  data = LifeCycleSavings
  )
summary(mreg1)
```

sdhjdjh
